### ISSUE TITLE
DVRP error

### ISSUE THREAD

**Issue by daisychang2309** [matsim-org/matsim-libs#1162] opened 2020-09-17 08:45 UTC
Hi, I want to simulate DVRP modes, and i tried to run DVRP code examples, but they all turned out to say "ctivityType_0 is deprecated config syntax; please use the more modern hierarchical format"

The full error log :
"2020-09-17 15:38:54,930  WARN PlanCalcScoreConfigGroup:152 activityType_0 is deprecated config syntax; please use the more modern hierarchical format; your output_config.xml will be in the correct version; the old version will fail eventually, since we want to reduce the workload on this backwards compatibility (look into PlanCalcScoreConfigGroup or PlanCalcRouteConfigGroup if you want to know what we mean).
2020-09-17 15:38:54,931  WARN PlanCalcScoreConfigGroup:166 activityTypicalDuration_0 is deprecated config syntax; please use the more modern hierarchical format; your output_config.xml will be in the correct version; the old version will fail eventually, since we want to reduce the workload on this backwards compatibility (look into PlanCalcScoreConfigGroup or PlanCalcRouteConfigGroup if you want to know what we mean).
2020-09-17 15:38:54,932  WARN PlanCalcScoreConfigGroup:152 activityType_1 is deprecated config syntax; please use the more modern hierarchical format; your output_config.xml will be in the correct version; the old version will fail eventually, since we want to reduce the workload on this backwards compatibility (look into PlanCalcScoreConfigGroup or PlanCalcRouteConfigGroup if you want to know what we mean).
2020-09-17 15:38:54,933  WARN PlanCalcScoreConfigGroup:166 activityTypicalDuration_1 is deprecated config syntax; please use the more modern hierarchical format; your output_config.xml will be in the correct version; the old version will fail eventually, since we want to reduce the workload on this backwards compatibility (look into PlanCalcScoreConfigGroup or PlanCalcRouteConfigGroup if you want to know what we mean).
2020-09-17 15:38:54,934  WARN PlanCalcScoreConfigGroup:152 activityType_2 is deprecated config syntax; please use the more modern hierarchical format; your output_config.xml will be in the correct version; the old version will fail eventually, since we want to reduce the workload on this backwards compatibility (look into PlanCalcScoreConfigGroup or PlanCalcRouteConfigGroup if you want to know what we mean).
2020-09-17 15:38:54,935  WARN PlanCalcScoreConfigGroup:166 activityTypicalDuration_2 is deprecated config syntax; please use the more modern hierarchical format; your output_config.xml will be in the correct version; the old version will fail eventually, since we want to reduce the workload on this backwards compatibility (look into PlanCalcScoreConfigGroup or PlanCalcRouteConfigGroup if you want to know what we mean).
2020-09-17 15:38:54,935  WARN PlanCalcScoreConfigGroup:152 activityType_3 is deprecated config syntax; please use the more modern hierarchical format; your output_config.xml will be in the correct version; the old version will fail eventually, since we want to reduce the workload on this backwards compatibility (look into PlanCalcScoreConfigGroup or PlanCalcRouteConfigGroup if you want to know what we mean).
2020-09-17 15:38:54,936  WARN PlanCalcScoreConfigGroup:166 activityTypicalDuration_3 is deprecated config syntax; please use the more modern hierarchical format; your output_config.xml will be in the correct version; the old version will fail eventually, since we want to reduce the workload on this backwards compatibility (look into PlanCalcScoreConfigGroup or PlanCalcRouteConfigGroup if you want to know what we mean).
2020-09-17 15:38:54,936  WARN PlanCalcScoreConfigGroup:201 traveling_drt_A is deprecated config syntax; please use the more modern hierarchical format; your output_config.xml will be in the correct version; the old version will fail eventually, since we want to reduce the workload on this backwards compatibility (look into PlanCalcScoreConfigGroup or PlanCalcRouteConfigGroup if you want to know what we mean).
2020-09-17 15:38:54,937  WARN PlanCalcScoreConfigGroup:201 traveling_drt_B is deprecated config syntax; please use the more modern hierarchical format; your output_config.xml will be in the correct version; the old version will fail eventually, since we want to reduce the workload on this backwards compatibility (look into PlanCalcScoreConfigGroup or PlanCalcRouteConfigGroup if you want to know what we mean).
2020-09-17 15:38:54,938  WARN PlanCalcScoreConfigGroup:201 traveling_drt_C is deprecated config syntax; please use the more modern hierarchical format; your output_config.xml will be in the correct version; the old version will fail eventually, since we want to reduce the workload on this backwards compatibility (look into PlanCalcScoreConfigGroup or PlanCalcRouteConfigGroup if you want to know what we mean).
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/C:/Users/ASUS/.m2/repository/com/google/inject/guice/4.1.0/guice-4.1.0.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
2020-09-17 15:38:57,513 ERROR MatsimRuntimeModifications:75 Getting uncaught Exception in Thread main
java.lang.RuntimeException: Unmaterialized config group: multiModeDrt
	at org.matsim.core.config.consistency.UnmaterializedConfigGroupChecker.checkConsistency(UnmaterializedConfigGroupChecker.java:32)
	at org.matsim.core.config.Config.checkConsistency(Config.java:225)
	at org.matsim.core.controler.ControlerUtils.checkConfigConsistencyAndWriteToLog(ControlerUtils.java:65)
	at org.matsim.core.controler.AbstractController$1.run(AbstractController.java:78)
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:69)
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:52)
	at org.matsim.core.controler.AbstractController.run(AbstractController.java:88)
	at org.matsim.core.controler.NewControler.run(NewControler.java:84)
	at org.matsim.core.controler.Controler.run(Controler.java:247)
	at org.matsim.project.RunMatsim.main(RunMatsim.java:55)
2020-09-17 15:38:57,516 ERROR MatsimRuntimeModifications:81 ERROR --- This is an unexpected shutdown!
2020-09-17 15:38:57,516 ERROR MatsimRuntimeModifications:84 Shutdown possibly caused by the following Exception:
java.lang.RuntimeException: Unmaterialized config group: multiModeDrt
	at org.matsim.core.config.consistency.UnmaterializedConfigGroupChecker.checkConsistency(UnmaterializedConfigGroupChecker.java:32)
	at org.matsim.core.config.Config.checkConsistency(Config.java:225)
	at org.matsim.core.controler.ControlerUtils.checkConfigConsistencyAndWriteToLog(ControlerUtils.java:65)
	at org.matsim.core.controler.AbstractController$1.run(AbstractController.java:78)
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:69)
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:52)
	at org.matsim.core.controler.AbstractController.run(AbstractController.java:88)
	at org.matsim.core.controler.NewControler.run(NewControler.java:84)
	at org.matsim.core.controler.Controler.run(Controler.java:247)
	at org.matsim.project.RunMatsim.main(RunMatsim.java:55)
2020-09-17 15:38:58,063 ERROR MatsimRuntimeModifications:99 ERROR --- MATSim unexpectedly terminated. Please check the output or the logfile with warnings and errors for hints.
2020-09-17 15:38:58,063 ERROR MatsimRuntimeModifications:100 ERROR --- results should not be used for further analysis.
2020-09-17 15:38:58,063 ERROR MatsimRuntimeModifications:104 ERROR --- This was an unexpected shutdown! See the log file for a possible reason.
Exception in thread "main" java.lang.RuntimeException: Unmaterialized config group: multiModeDrt
	at org.matsim.core.config.consistency.UnmaterializedConfigGroupChecker.checkConsistency(UnmaterializedConfigGroupChecker.java:32)
	at org.matsim.core.config.Config.checkConsistency(Config.java:225)
	at org.matsim.core.controler.ControlerUtils.checkConfigConsistencyAndWriteToLog(ControlerUtils.java:65)
	at org.matsim.core.controler.AbstractController$1.run(AbstractController.java:78)
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:69)
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:52)
	at org.matsim.core.controler.AbstractController.run(AbstractController.java:88)
	at org.matsim.core.controler.NewControler.run(NewControler.java:84)
	at org.matsim.core.controler.Controler.run(Controler.java:247)
	at org.matsim.project.RunMatsim.main(RunMatsim.java:55)

The simulation did not run properly. Error/Exit code: 1"

This is crucial for my research I would be really grateful for your help.

**Comment by michalmac** [comment] 2020-09-24 14:00
duplicate of https://github.com/matsim-org/matsim-code-examples/issues/433

**Closed by michalmac** 2020-09-24 14:00 UTC
