### ISSUE TITLE
OTFVis clashes with new mac OS

### ISSUE THREAD

**Issue by tthunig** [matsim-org/matsim-libs#972] opened 2020-04-23 18:38 UTC
When using OTFVis (with or without signals) the Java application terminates at the moment just before creating the OTFVis window (after the simulation started) with the following exception:

> *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'NSWindow drag regions should only be invalidated on the Main Thread!'
> *** First throw call stack:
> (
> 	0   CoreFoundation                      0x00007fff3460a8ab __exceptionPreprocess + 250
> 	1   libobjc.A.dylib                     0x00007fff6a6e2805 objc_exception_throw + 48
> 	2   CoreFoundation                      0x00007fff3463330c -[NSException raise] + 9
> 	3   AppKit                              0x00007fff31783538 -[NSWindow(NSWindow_Theme) _postWindowNeedsToResetDragMarginsUnlessPostingDisabled] + 310
> 	4   AppKit                              0x00007fff3176aed5 -[NSWindow _initContent:styleMask:backing:defer:contentView:] + 1416
> 	5   AppKit                              0x00007fff3176a947 -[NSWindow initWithContentRect:styleMask:backing:defer:] + 42
> 	6   libnativewindow_macosx.jnilib       0x0000000131da23fe Java_jogamp_nativewindow_macosx_OSXUtil_CreateNSWindow0 + 398
> 	7   ???                                 0x000000011bec0c90 0x0 + 4763421840
> )
> libc++abi.dylib: terminating with uncaught exception of type NSException
> 
> The simulation did not run properly. Error/Exit code: 134

The problem seems to lie in the fact that on new mac OS windows can only be generated out of the [main thread](https://trac.macports.org/ticket/58794). Does anybody know how to start OTFVis from the main thread?
Maybe @michaz or @Janekdererste ?

On Windows or older Mac versions this problem does not occur...

This problem is somehow urgent because it affects teaching...

**Comment by kainagel** [comment] 2020-04-23 19:17
Also https://jogamp.org/bugzilla/show_bug.cgi?id=1370 .
Does not feel easy to fix since the design is the other way around: We run matsim (more specifically, the qsim) in the main thread, and _sometimes_ attach otfvis.  
@mrieser (and @michaz , but he is already mentioned above) are you more optimistic about this?
:-(

**Comment by mrieser** [comment] 2020-04-23 19:21
I think "main thread" here mains on the native main thread, not on the Java main thread. Which probably makes it even more difficult to fix.

**Comment by mrieser** [comment] 2020-04-23 19:24
> Also https://jogamp.org/bugzilla/show_bug.cgi?id=1370 .

This states it was fixed in 2.4.0. I would try to update all the `org.jogamp` dependencies from `2.3.2` to `2.4.0` in the otfvis-contrib.

**Comment by mrieser** [comment] 2020-04-23 19:27
Oh, 2.4.0 is still in development, 2.3.2 is the latest...

**Comment by mrieser** [comment] 2020-04-23 19:35
Not helpful, but: Apple deprecated OpenGL two years ago. I assume that it won't be supported anymore in one or two years time, and then OTFVis will definitely stop working...

**Comment by michaz** [comment] 2020-04-23 22:25
I'd like to have a look, but I'm not running Catalina and not even Mojave, so I don't see the warning. :-/

**Comment by kainagel** [comment] 2020-04-24 07:28
https://www.gamefromscratch.com/post/2018/06/13/Cross-Platform-OpenGL-Alternatives.aspx (not making me optimistic)

**Comment by kainagel** [comment] 2020-04-24 07:42
It looks a bit like one might be able to get somewhat stable development builds: https://jogamp.org/deployment/archive/master/?C=M;O=D .  I can't fully figure out how this is plugged together without trying it but it looks either similar to the native library stuff we have used in other places, or even simpler (in the sense that we bind jars and not dlls).

Might be a solution for ourselves.  Is probably not a solution for shipping until 2.4.x is mavenized.

**Comment by jfbischoff** [comment] 2020-04-24 09:29
For teaching purposes and as a rather quick fix, you could consider switching to a Linux VM, running via Virtual Box or similar. Not perfect, but might actually reduce some overall maintenance trouble, as every student has exactly the same setup.

**Comment by kainagel** [comment] 2020-04-25 10:03
A quick note that I just had some success with the development build.  Need to run to some other things now ...

**Comment by kainagel** [comment] 2020-04-25 12:17
Ok, I can confirm now that this seems to work.  I tested within the otfvis contrib, and within vsptelematics, which uses otfvis.  The steps are very roughly
* download from https://jogamp.org/deployment/archive/master/?C=M;O=D (I used gluegen_937_...).
* add as native library (in intellij this goes via File → ProjectStructure; I think one can add it as "Global Library"; I still had to add it individually to each module that uses it; and within the modules I had to set the scope from "compile" to "runtime").
@mrieser , thank you so much for providing the correct hint.

I can't say what might be a good way to package.  I tried using `mvn install` but failed; possibly, there is some trickery that makes the "general" jar fall back onto the true hardware-dependent library, or maybe something else.  Even then, we would still need to figure out how to ship this.   (@michaz , @mrieser, any ideas?)

Finally, we would need to decide if we make the otfvis contrib in general depend on something like this when only mac users need this.  (Given how many mac users we have at vsp, and given how many of those use otfvis, and given that students with their own laptops seem to have the same problem, I would have a tendency to answer this question with "yes".)

**Comment by mrieser** [comment] 2020-04-28 15:32
`mvn install` probably fails as Maven does not know about the manually downloaded jar-files, as you set this up only in IntelliJ, but not in the pom.xml. So we essentially need to change the `pom.xml` to point to these newer jar-files. It could be done with a `<scope>system</scope>`, but then it would only work within the `otfvis` contrib, but not in other contribs that use otfvis as a dependency.

I could host the two files in my maven-repository, and we could adapt the pom accordingly to use those jars instead of the default ones. And once 2.4.0 is officially released, we could switch back to the official libraries.

**Comment by kainagel** [comment] 2020-04-28 20:05
I meant I tried something like this:
```
mvn install:install-file -Dfile=<path-to-file> -DgroupId=<group-id> \
    -DartifactId=<artifact-id> -Dversion=<version> -Dpackaging=<packaging>
```
Mirroring all the entries we have for 2.3.2 except for the version number.  And wasn't able to make it work on first attempt.

But in general, self-hosting should be a way to make it work, I agree.

**Comment by kainagel** [comment] 2020-11-02 09:41
Is anybody aware about progress here?  I am again teaching, and it would save me 45min of valuable teaching time.

Could we host it ourselves?  (Unfortunately I do not know how to do that.)

**Comment by lennsea** [comment] 2020-11-02 16:08
This describes the process of making OTFVis work on MacOS, based on @kainagel's [recommendations](https://github.com/matsim-org/matsim-libs/issues/972#issuecomment-619370785):

1. inside a directory of your choice, download the required files using your terminal: 
`wget --recursive --no-parent https://jogamp.org/deployment/archive/master/gluegen_937-joal_660-jogl_1506-jocl_1147/`
(If you don't have wget installed, install wget using `brew install wget`. If you don't have homebrew installed, install [homebrew](https://brew.sh))
1. Via `IntelliJ > File > Project Structure > Platform Settings > Global Libraries`, add `.../jogamp.org/deployment/archive/master/gluegen_937-joal_660-jogl_1506-jocl_1147/jar/gluegen-rt.jar` and `.../jogamp.org/deployment/archive/master/gluegen_937-joal_660-jogl_1506-jocl_1147/jar/jogl-all.jar` as a new Java Global Library from your freshly defined directory.
![Bildschirmfoto 2020-11-02 um 16 50 27](https://user-images.githubusercontent.com/31455226/97889171-55316880-1d2c-11eb-950e-b0690a098440.png)
![Bildschirmfoto 2020-11-02 um 16 50 54](https://user-images.githubusercontent.com/31455226/97889190-58c4ef80-1d2c-11eb-911b-64170f1e1221.png)
Your global libraries should then show something like this:
![Bildschirmfoto 2020-11-02 um 16 57 13](https://user-images.githubusercontent.com/31455226/97890509-e6550f00-1d2d-11eb-87e5-cd7dd75607e3.png)

1. Then via `Project Structure > Project Settings > Modules`, find your added modules, **move them to the top of the list** and **change their scope to runtime**
![Bildschirmfoto 2020-11-02 um 16 57 47](https://user-images.githubusercontent.com/31455226/97890210-90806700-1d2d-11eb-966c-5cadbe5407d3.png)

**Closed** 2020-11-26 22:36 UTC
Labels: bug
