### ISSUE TITLE
Problem with enforced charging times (PR #2944)

### ISSUE THREAD

**Issue by tobias-tietz** [matsim-org/matsim-libs#3033] opened 2024-01-02 15:05 UTC
I want to use the new enforced charging times introduced in PR #2944. As soon as the first queues appear, an error occurs (see attachment). I can't find a solution to this problem, does anyone have any ideas?

Output log: 
[output_log_simulation.txt](https://github.com/matsim-org/matsim-libs/files/13811180/output_log_simulation.txt)

**Comment by steffenaxer** [comment] 2024-01-02 19:21
So in your setup is no eDrt involved so the root cause of the problem is different. I think @tschlenther may check this code.

**Comment by tobias-tietz** [comment] 2024-01-05 11:16
Thank you anyway @steffenaxer !

**Comment by tschlenther** [comment] 2024-01-05 12:01
Hi,
thanks for reporting this. I will have a closer look after my return, in the second half of January.
The log (lines 2059ff) indicates that an agent quits a queue without that the charging process started. 
An error message is thrown because you are using the switch to enforce charging duration, which means that the agent should not quit the queue nor the charging process early. 
To use some of the time before my return, maybe you @tobias-tietz can find out (by outcommenting RuntimeException and/or running in debug mode), why and where the QuitQueueAtChargerEvent occured in your simulation?

**Comment by tschlenther** [comment] 2024-01-19 12:05
closing this issue, as the problem was caused by the fact that Tobias accidentally instantiated a `QuitQueueAtChargerEvent` when a vehicles is moved from the queue and gets plugged in. He works on a separate fork, thus this problem does not exist in matsim-libs. 
Background: The `QuitQueueAtChargerEvent` is (currently) only thrown if a vehicle quits the charger queue without having been charged. The event sequence collector as well as the code for enforcing the planned charging duration relies on that fact.

**Closed by tschlenther** 2024-01-19 12:05 UTC
Labels: bug
