### ISSUE TITLE
Running MAAS and SwissRailRaptor modules together

### ISSUE THREAD

**Issue by vsgo222** [matsim-org/matsim-libs#1624] opened 2021-08-16 02:21 UTC
Hi,
I am trying to run MATSim on San Francisco city area with modes car, drt, pt. Since, SwissRailRaptor is now the default router, I have not made any override settings to call the module explicitly and therefore using [MATSim-MAAS](https://github.com/matsim-org/matsim-maas). Howeover I get the following error:
`1) [Guice/ErrorInCustomProvider]: NullPointerException
  while locating SwissRailRaptorFactory
  at SwissRailRaptorRoutingModuleProvider.<init>(SwissRailRaptorRoutingModuleProvider.java:28)
      \_ for 1st parameter
  while locating SwissRailRaptorRoutingModuleProvider
  while locating RoutingModule annotated with @Named(value="pt")
  while locating RoutingModule annotated with @Element(setName=,uniqueId=130, type=MAPBINDER, keyType=String)
  at TripRouter.<init>(TripRouter.java:103)
  while locating TripRouter`
I can't figure out what the error is about? Can someone help me in understanding why I get the error and how it could be handled? 
I am also reviewing the MATSim-Berlin scenario which has PT, DRT modes but creates a custom config, scenario, and controller. There is a comment which states the following
`use the main mode identifier which knows how to handle intermodal trips generated by the used sbb pt raptor router the SwissRailRaptor already binds its IntermodalAwareRouterModeIdentifier, however, drt obviously replaces it with its own implementation`, so does it mean that I need a custom class similar to the one found for MATSim-Berlin? If yes, is there any guide that can help me to build it with all relevant dependencies or MATSim-Berlin (OpenBerlinScenario.java) could be used to run it? 
[output.zip](https://github.com/matsim-org/matsim-libs/files/6989388/output.zip)

**Comment by michalmac** [comment] 2021-08-19 11:26
Closing this one as a duplicate of https://github.com/matsim-org/matsim-code-examples/issues/602

**Closed by michalmac** 2021-08-19 11:26 UTC
